name: Kubernetes CI

on:
  push: 
    branches: 
      - main

jobs:
  pyapp-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: "docker build -t zchege/gha-pyapp:$GITHUB_SHA ."
      
    
